# eslint-disable pnpm/yaml-no-duplicate-catalog-item

minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
shellEmulator: true

packages:
  - docs
  - docs-v0
  - examples/*
  - packages/*

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  protobufjs: false
  sharp: false

onlyBuiltDependencies:
  - unrs-resolver

catalog:
  '@antfu/eslint-config': ^9.5.1
  '@hey-api/openapi-ts': ^0.99.0
  '@moeru/eslint-config': ^0.1.0-beta.20
  '@moeru/tsconfig': ^0.1.0-beta.20
  '@nolebase/vitepress-plugin-git-changelog': ^2.18.2
  '@nolebase/vitepress-plugin-highlight-targeted-heading': ^2.18.2
  '@nolebase/vitepress-plugin-inline-link-preview': ^2.18.2
  '@nolebase/vitepress-plugin-meta': ^2.18.2
  '@pnpm/find-workspace-dir': ^1000.1.5
  '@shikijs/magic-move': ^4.4.3
  '@shikijs/vitepress-twoslash': ^4.5.0
  '@standard-schema/spec': 1.1.0
  '@types/json-schema': ^7.0.15
  '@types/node': ^26.6.4
  '@vitest/coverage-v8': ^5.0.3
  '@voidzero-dev/vitepress-theme': ^5.0.7
  animejs: ^4.5.0
  automd: ^0.4.3
  bumpp: ^12.3.0
  eslint: ^10.12.0
  eslint-plugin-oxlint: ^1.87.0
  eventsource-parser: ^4.1.1
  oxlint: ^1.87.0
  pkg-pr-new: ^0.0.90
  pkgroll: ^2.28.1
  rolldown: ^1.2.12
  shiki: ^4.4.3
  tsdown: ^0.23.0
  tsx: ^4.23.15
  turbo: ^2.11.7
  typescript: ~6.0.3
  vitepress: ^2.0.0-alpha.20
  vitepress-plugin-llms: ^1.14.0
  vitest: ^5.0.3
  vue: ^3.5.43

catalogs:
  schema:
    '@valibot/to-json-schema': ^1.0.0
    arktype: ^2.1.20
    effect: ^3.16.0
    sury: ^10.0.0 || ^11.0.0-alpha
    valibot: ^1.0.0
    zod: ^3.25.0 || ^4.0.0
    zod-to-json-schema: ^3.25.0
  schema-dev:
    arktype: ^2.2.0
    effect: ^3.21.0
    sury: ^11.0.0-alpha.4
    zod: ^4.3.6
