packages:
  - docs
  - packages/*
  - packages-ext/*
catalog:
  '@valibot/to-json-schema': ^1.0.0-rc.0
  valibot: ^1.0.0-rc.3

  arktype: ^2.0.4

  zod: ^3.24.2
  zod-to-json-schema: ^3.24.3

  type-fest: ^4.35.0
