# eslint-disable pnpm/yaml-no-duplicate-catalog-item

minimumReleaseAgeExclude:
  - lucide-react@1.37.0

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - docs
  - examples/*
  - packages/*
  - packages-ext/*
  - packages-top/*

catalog:
  '@antfu/eslint-config': ^9.5.1
  '@moeru/eslint-config': ^0.1.0-beta.20
  '@moeru/tsconfig': ^0.1.0-beta.20
  '@pnpm/find-workspace-dir': ^1000.1.5
  '@standard-schema/spec': 1.1.0
  '@types/json-schema': ^7.0.15
  '@types/node': ^26.4.0
  '@vitest/coverage-v8': ^5.0.0
  automd: ^0.4.3
  bumpp: ^12.3.0
  eslint: ^10.10.0
  eslint-plugin-oxlint: ^1.82.0
  oxlint: ^1.82.0
  pkgroll: ^2.28.1
  tsdown: ^0.23.0
  tsx: ^4.23.13
  turbo: ^2.10.12
  typescript: ~6.0.3
  vitest: ^5.0.0

catalogs:
  schema:
    '@valibot/to-json-schema': ^1.0.0
    arktype: ^2.1.20
    effect: ^3.16.0
    sury: ^10.0.0 || ^11.0.0-alpha
    valibot: ^1.0.0
    zod: ^3.25.0 || ^4.0.0
    zod-to-json-schema: ^3.25.0
  schema-dev:
    arktype: ^2.2.0
    effect: ^3.21.0
    sury: ^11.0.0-alpha.4
    zod: ^4.3.6

onlyBuiltDependencies:
  - unrs-resolver

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  protobufjs: false
  sharp: false
