shellEmulator: true

trustPolicy: no-downgrade

packages:
  - docs
  - examples/*
  - packages/*
  - packages-ext/*
  - packages-top/*

catalog:
  '@antfu/eslint-config': ^6.7.3
  '@langfuse/otel': ^4.5.1
  '@moeru/eslint-config': &std ^0.1.0-beta.14
  '@moeru/std': *std
  '@moeru/tsconfig': *std
  '@opentelemetry/api': ^1.9.0
  '@opentelemetry/sdk-trace-base': ^2.2.0
  '@opentelemetry/sdk-trace-node': ^2.2.0
  '@orama/orama': ^3.1.18
  '@pnpm/find-workspace-dir': ^1000.1.3
  '@standard-schema/spec': ^1.1.0
  '@tailwindcss/postcss': ^4.1.18
  '@types/eslint': ^9.6.1
  '@types/json-schema': ^7.0.15
  '@types/mdx': ^2.0.13
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitest/coverage-v8': &vitest ^4.0.16
  automd: ^0.4.2
  best-effort-json-parser: ^1.2.1
  bumpp: ^10.3.2
  clsx: ^2.1.1
  dotenv: ^17.2.3
  eslint: ^9.39.2
  fumadocs-core: ^16.4.1
  fumadocs-mdx: ^14.2.3
  fumadocs-twoslash: ^3.1.10
  fumadocs-ui: ^16.4.1
  lucide-react: ^0.562.0
  next: ^16.1.1
  pkgroll: ^2.21.4
  postcss: ^8.5.6
  react: ^19.2.3
  react-dom: ^19.2.3
  recharts: ^2.15.4
  remark: ^15.0.1
  remark-gfm: ^4.0.1
  remark-mdx: ^3.1.1
  scule: ^1.3.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tsdown: ^0.18.3
  tsx: ^4.21.0
  turbo: ^2.7.2
  tw-animate-css: ^1.4.0
  twoslash: ^0.3.6
  type-fest: ^5.3.1
  typescript: ^5.9.3
  vitest: *vitest

catalogs:
  schema:
    '@valibot/to-json-schema': &valibot ^1.0.0
    arktype: ^2.1.20
    effect: ^3.16.0
    sury: ^10.0.0
    valibot: *valibot
    zod: ^3.25.0 || ^4.0.0
    zod-to-json-schema: ^3.25.0

  schema-dev:
    arktype: ^2.1.29
    effect: ^3.19.13
    sury: ^11.0.0-alpha.4
    zod: ^4.2.1
onlyBuiltDependencies:
  - unrs-resolver
