packages:
  - docs
  - examples/*
  - packages/*
  - packages-ext/*
  - packages-top/*

catalog:
  type-fest: ^4.35.0

catalogs:
  schema:
    '@valibot/to-json-schema': ^1.0.0
    valibot: ^1.0.0

    arktype: ^2.1.10

    effect: ^3.14.1

    zod: ^3.24.2
    zod-to-json-schema: ^3.24.4
