import type { InputFileContent, InputImageContent, InputTextContent, InputVideoContent, OutputTextContent, ReasoningSummaryContent, RefusalContent } from './content'
import type { FunctionCallStatus } from './misc'

/** @see {@link https://www.openresponses.org/reference#object-SystemMessageItemParam} */
export interface AssistantMessageItem extends MessageItem<'assistant', OutputTextContent | RefusalContent> {}

/** @see {@link https://www.openresponses.org/reference#object-DeveloperMessageItemParam} */
export interface DeveloperMessageItem extends MessageItem<'developer', InputTextContent> {}

/** @see {@link https://www.openresponses.org/reference#object-FunctionCallItemParam} */
export interface FunctionCallItem extends Item<'function_call'> {
  /** The function arguments as a JSON string. */
  arguments: string
  /** The unique ID of the function tool call generated by the model. */
  call_id: string
  /** The name of the function to call. */
  name: string
  /** The status of the function tool call. */
  status?: FunctionCallStatus
}

/**
 * The output of a function tool call.
 * @see {@link https://www.openresponses.org/reference#object-FunctionCallOutputItemParam}
 */
export interface FunctionCallOutputItem extends Item<'function_call_output'> {
  /** The unique ID of the function tool call generated by the model. */
  call_id: string
  output: (InputFileContent | InputImageContent | InputTextContent | InputVideoContent)[] | string
  /** The status of the function tool call. */
  status?: FunctionCallStatus
}

/** Context to provide to the model for the scope of this request. May either be a string or an array of input items. If a string is provided, it is interpreted as a user message. */
export type Input = AssistantMessageItem | DeveloperMessageItem | FunctionCallItem | FunctionCallOutputItem | ItemReference | ReasoningItem | SystemMessageItem | UserMessageItem

/**
 * An internal identifier for an item to reference.
 * @see {@link https://www.openresponses.org/reference#object-ItemReferenceParam}
 */
export interface ItemReference {
  /** The ID of the item to reference. */
  id: string
  type: 'item_reference'
}

/** @see {@link https://www.openresponses.org/reference#object-ReasoningItemParam} */
export interface ReasoningItem extends Item<'reasoning'> {
  content?: unknown
  encrypted_content?: unknown
  /** Reasoning summary content associated with this item. */
  summary: ReasoningSummaryContent[]
}

/** @see {@link https://www.openresponses.org/reference#object-SystemMessageItemParam} */
export interface SystemMessageItem extends MessageItem<'system', InputTextContent> {}

/** @see {@link https://www.openresponses.org/reference#object-UserMessageItemParam} */
export interface UserMessageItem extends MessageItem<'user', InputFileContent | InputImageContent | InputTextContent> {}

interface Item<T extends string> {
  /** The unique ID of this item. */
  id?: string
  /** The item type. */
  type: T
}

interface MessageItem<T extends string, C> extends Item<'message'> {
  /** The message content, as an array of content parts. */
  content: C[] | string
  /** The message role. */
  role: T
  /** The status of the message item. */
  status?: string
}
