import type { InputTextContent } from './content'
import type { FunctionCallItem, FunctionCallOutputItem } from './input'
import type { FunctionCallStatus } from './misc'

/**
 * A message to or from the model.
 * @see {@link https://www.openresponses.org/reference#object-Message}
 */
export interface Message {
  content: InputTextContent[]
  id: string
  role: 'assistant' | 'developer' | 'system' | 'user' | (string & {})
  status: FunctionCallStatus
  type: 'message'
}

export type Output = FunctionCallItem | FunctionCallOutputItem | Message | ReasoningBody

/**
 * A reasoning item that was generated by the model.
 * @see {@link https://www.openresponses.org/reference#object-ReasoningBody}
 */
export interface ReasoningBody {
  content?: InputTextContent[]
  encrypted_content?: string
  id: string
  summary: InputTextContent[]
  type: 'reasoning'
}
