import type { IncompleteDetails } from './misc'
import type { Output } from './output'
import type { FunctionTool, ToolChoice } from './tool'

/** @see {@link https://www.openresponses.org/reference#body-1} */
export interface OpenResponsesResponse {
  /** The Unix timestamp (in seconds) for when the response was completed, if it was completed. */
  completed_at: number
  /** The Unix timestamp (in seconds) for when the response was created. */
  created_at: number
  /** The error that occurred, if the response failed. */
  error?: {
    /** A machine-readable error code that was returned. */
    code: string
    /** A human-readable description of the error that was returned. */
    message: string
  }
  /** The unique ID of the response that was created. */
  id: string
  /** Details about why the response was incomplete, if applicable. */
  incompleteDetails: IncompleteDetails
  /** Additional instructions that were used to guide the model for this response. */
  instructions: string
  /** The model that generated this response. */
  model: string
  /** The object type, which was always `response`. */
  object: 'response'
  /** The output items that were generated by the model. */
  output: Output[]
  /** Whether the model was allowed to call multiple tools in parallel. */
  parallel_tool_calls: boolean
  /** The ID of the previous response in the chain that was referenced, if any. */
  previous_response_id: string
  /** The status that was set for the response. */
  status: string
  tool_choice: ToolChoice
  /** The tools that were available to the model during response generation. */
  tools: FunctionTool[]
  /** How the input was truncated by the service when it exceeded the model context window. */
  truncation: 'auto' | 'disabled'
}
