import { defineConfig } from '@hey-api/openapi-ts'

const removeDiscriminator = (data: unknown): unknown => {
  if (Array.isArray(data))
    return data.map(removeDiscriminator)

  if (data !== null && typeof data === 'object') {
    return Object.fromEntries(
      Object.entries(data)
        .filter(([key]) => key !== 'discriminator')
        .map(([key, value]) => [key, removeDiscriminator(value)]),
    )
  }

  return data
}

const path = await fetch('https://www.openresponses.org/openapi/openapi.json')
  .then(async res => res.json())
  .then(removeDiscriminator)

export default defineConfig({
  input: { path },
  output: {
    header: [
      '/* eslint-disable sonarjs/use-type-alias */',
      '// This file is auto-generated by @hey-api/openapi-ts',
    ],
    path: 'src/generated',
    postProcess: ['eslint', 'oxlint'],
  },
  plugins: ['@hey-api/typescript'],
})
